"""The nodes the Explorer and the IIIF documents read, by role.

A role names a node by the slug of its resource model and its alias
(``role_node``); no graph or node id is written in the code.
"""

ROLES = {
    "doc_name": ("document", "label_of_name"),
    "doc_manifest": ("document", "facsimiles"),
    "doc_owner": ("document", "current_owner"),
    "doc_identifier": ("document", "value_of_identifier"),
    "doc_identifier_type": ("document", "type_of_identifier"),
    "doc_start": ("document", "date_start_of_production_time"),
    "doc_end": ("document", "date_end_of_production_time"),
    "doc_description": ("document", "content_of_statement"),
    "doc_type": ("document", "type"),
    "comp_zone": ("component", "location_in_document"),
    "comp_type": ("component", "type"),
    "comp_colour": ("component", "color_features"),
    "an_name": ("analysis", "label_of_name"),
    "technique": ("analysis", "analysis_technique_used"),
    "operators": ("analysis", "performed_by_actor"),
    "start": ("analysis", "analysis_start_date"),
    "end": ("analysis", "analysis_end_date"),
    "files": ("analysis", "measurement_point_data"),
    "micro": ("analysis", "micro_macro_imaging"),
    "imaging": ("analysis", "chemical_imaging_manifest"),
    "zone": ("analysis", "literal_location_of_analysis"),
    "dataset": ("analysis", "dataset_url"),
    "bibliography": ("analysis", "bibliographic_title"),
    "statement_type": ("analysis", "type_of_statement"),
    "statement_content": ("analysis", "content_of_statement"),
    "instrument": ("analysis", "instrument"),
    "material": ("characterization", "identified_material"),
    "confidence": ("characterization", "material_confidence"),
    "colour": ("characterization", "color_aspect"),
    "layer": ("characterization", "layer_type"),
    "elements": ("characterization", "detected_elements"),
    "element_level": ("characterization", "element_level"),
    "ch_zone": ("characterization", "location_of_characterization"),
    "ch_note": ("characterization", "inference_making"),
    "ch_authors": ("characterization", "authors_of_inference"),
    "ch_start": ("characterization", "inference_making_start_date"),
    "ch_end": ("characterization", "inference_making_end_date"),
    "ch_source": ("characterization", "source_of_statement"),
    "sample_zone": ("sample", "location_in_object_of_sampling_taking"),
    "component_observed": ("analysis", "component_observed"),
    "analysis_by_project": ("analysis", "analysis_by_project"),
    "sample_used": ("analysis", "sample_used"),
    "item_visual_is_part_of_document": ("component", "item_visual_is_part_of_document"),
    "comp_name": ("component", "label_of_name"),
    "object_observed": ("characterization", "object_observed"),
    "evidence_analyses": ("characterization", "evidence_analyses"),
    "project_name": ("project", "label_of_name"),
}
