# Generated by Django 5.2.6 on 2026-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RendererConfig",
            fields=[
                (
                    "configid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("rendererid", models.UUIDField()),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("config", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "renderer_config",
                "managed": True,
            },
        ),
    ]
