"""Install the data-version ledger ``ms_data_change`` and its statement triggers.

Generated by ``makemigrations`` from ``manuspectrum/sql_config.py``. The
dependencies name the migrations that create the watched tables, so each
table exists when the triggers are created.
"""

# Generated by Django 5.2.16 on 2026-09-25 15:41

import django_migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuspectrum", "0005_sample_summary_hop"),
        ("models", "7783_add_graph_publications"),
        ("models", "5972_iiifmanifest"),
        ("arches_controlled_lists", "0001_initial"),
        ("guardian", "0001_initial"),
        ("auth", "0001_initial"),
    ]

    operations = [
        django_migrate_sql.operations.CreateSQL(
            name="ms_data_change",
            sql="-- Data version of the Explorer's memos: every writing statement on a table\n-- the Explorer reads leaves one row per transaction in `ms_data_change`, and\n-- `(count(*), max(seq))` names the committed state. A second statement of the\n-- same transaction gives its row a new `seq`, so a reader inside that\n-- transaction sees the version move too. One row per transaction, not a\n-- counter row: two writing transactions never wait on each other here.\n--\n-- A trigger is created only on the tables that exist when this runs.\n\nCREATE TABLE IF NOT EXISTS ms_data_change (\n    seq bigserial PRIMARY KEY,\n    txid bigint NOT NULL UNIQUE,\n    at timestamptz NOT NULL DEFAULT now()\n);\n\nCREATE OR REPLACE FUNCTION ms_data_change() RETURNS trigger\nLANGUAGE plpgsql AS $body$\nBEGIN\n    INSERT INTO ms_data_change (txid) VALUES (txid_current())\n    ON CONFLICT (txid) DO UPDATE\n        SET seq = nextval('ms_data_change_seq_seq'), at = now();\n    RETURN NULL;\nEND\n$body$;\n\nDO $do$\nDECLARE\n    watched text;\nBEGIN\n    FOREACH watched IN ARRAY ARRAY['tiles', 'resource_instances', 'resource_x_resource', 'iiif_manifests', 'arches_controlled_lists_listitem', 'arches_controlled_lists_listitemvalue', 'graphs_x_published_graphs', 'renderer_config', 'guardian_userobjectpermission', 'guardian_groupobjectpermission', 'auth_user_groups', 'auth_group_permissions', 'auth_user_user_permissions'] LOOP\n        IF to_regclass(watched) IS NOT NULL THEN\n            EXECUTE format('DROP TRIGGER IF EXISTS ms_data_change ON %I', watched);\n            EXECUTE format(\n                'CREATE TRIGGER ms_data_change'\n                ' AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON %I'\n                ' FOR EACH STATEMENT EXECUTE FUNCTION ms_data_change()',\n                watched\n            );\n        END IF;\n    END LOOP;\nEND\n$do$;\n",
            reverse_sql="DO $do$ DECLARE watched text; BEGIN FOREACH watched IN ARRAY ARRAY['tiles', 'resource_instances', 'resource_x_resource', 'iiif_manifests', 'arches_controlled_lists_listitem', 'arches_controlled_lists_listitemvalue', 'graphs_x_published_graphs', 'renderer_config', 'guardian_userobjectpermission', 'guardian_groupobjectpermission', 'auth_user_groups', 'auth_group_permissions', 'auth_user_user_permissions'] LOOP IF to_regclass(watched) IS NOT NULL THEN EXECUTE format('DROP TRIGGER IF EXISTS ms_data_change ON %I', watched); END IF; END LOOP; END $do$; DROP FUNCTION IF EXISTS ms_data_change(); DROP TABLE IF EXISTS ms_data_change;",
        ),
    ]
