"""
IMPORT RELATIONSHIPS FROM CSV TO RESOURCEXRESOURCE

CONTEXT & PROBLEM:
Following the relationship export (export_relations_csv.py), this script
recreates missing entries in the ResourceXResource table while ensuring:
1. Relationships have been manually validated (via Excel/LibreOffice)
2. Only relationships marked 'CREATE' are imported
3. Invalid relationships are ignored
4. The process is transactional (all or nothing per batch)

OBJECTIVE:
Restore consistency between tile data and the ResourceXResource table
to guarantee optimal performance for relational queries and APIs.

HOW IT WORKS:
1. Reads CSV generated by export_relations_csv.py
2. Filters rows based on 'action' column:
   - CREATE: Creates relationship in ResourceXResource
   - SKIP: Ignores (relationship already exists or unwanted)
   - ERROR: Automatically ignores (invalid target)
3. Creates relationships in batches with atomic transactions
4. Uses get_or_create to avoid duplicates
5. Continues or stops based on --skip-errors option

IMPORTANT OPTIONS:
--dry-run: Simulates import without modifications (ALWAYS test with this first!)
--skip-errors: Continues even if some relationships fail
--batch-size: Transaction size (default 100, increase for large databases)

RECOMMENDED WORKFLOW:
1. python manage.py export_relations_csv --output relations.csv
2. Open relations.csv in Excel, validate, modify 'action' column if needed
3. python manage.py import_relations_csv --input relations.csv --dry-run
4. Verify output, then run without --dry-run

SAFETY:
- Atomic transactions per batch (rollback on error)
- Validation of source and target resource existence
- No deletion, only creation (safe by default)
- Uses get_or_create (no duplication even if re-run)

IMPACT:
After import, all APIs and views using ResourceXResource will immediately
see the relationships.

RELATIONSHIP TYPES:
In modern Arches (7+), relationshiptype is a UUID referencing RDM concepts.
Legacy entries may use string values like "related".

This script auto-detects the preferred format from existing relations:
- If UUID found: Uses UUID format (recommended)
- If only "related" found: Uses "related" string
- Default: 'ac41d9be-79db-4256-b368-2f4559cfbe55' ("is related to" concept)

You can override with --relationship-type flag.
"""

from django.core.management.base import BaseCommand
from django.db import transaction
from arches.app.models.resource import Resource
from arches.app.models.models import ResourceXResource, Node, Value
from arches.app.models.tile import Tile
import csv
from uuid import UUID
from datetime import datetime
from collections import Counter


class Command(BaseCommand):
    help = "Imports relationships from validated CSV to ResourceXResource (complete by default)"

    def add_arguments(self, parser):
        # Required
        parser.add_argument(
            "--input",
            type=str,
            required=True,
            help="Path to input CSV file",
        )

        # Behavior
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Simulate import without modifications",
        )
        parser.add_argument(
            "--skip-errors",
            action="store_true",
            help="Continue even if some relationships fail",
        )

        # Performance
        parser.add_argument(
            "--batch-size",
            type=int,
            default=100,
            help="Batch size for transactions (default: 100)",
        )

        # Exclusions
        parser.add_argument(
            "--exclude-tile",
            action="store_true",
            help="Do NOT link ResourceXResource to source tile",
        )
        parser.add_argument(
            "--exclude-node",
            action="store_true",
            help="Do NOT link ResourceXResource to specific node",
        )
        parser.add_argument(
            "--exclude-notes",
            action="store_true",
            help="Do NOT add auto-generated notes",
        )

        # Relationship type
        parser.add_argument(
            "--relationship-type",
            type=str,
            default=None,
            help='Relationship type: UUID from RDM or "related" (auto-detected if not specified)',
        )
        parser.add_argument(
            "--force-uuid",
            action="store_true",
            help="Force UUID format even if string format is more common",
        )

    def get_default_relationship_type(self, force_uuid=False):
        """
        Auto-detect the relationship type from existing relations.
        Prefers UUID format if available, unless legacy string is more common.

        Returns a tuple: (relationshiptype, inverserelationshiptype)
        """
        # Get all unique relationship types
        all_rels = ResourceXResource.objects.filter(
            relationshiptype__isnull=False
        ).values("relationshiptype", "inverserelationshiptype")

        if not all_rels:
            self.stdout.write(
                self.style.WARNING("  No existing relations found, using default UUID")
            )
            # Default UUID for "is related to" (both directions same)
            default_uuid = "ac41d9be-79db-4256-b368-2f4559cfbe55"
            return (default_uuid, default_uuid)

        # Count occurrences
        type_counts = Counter(r["relationshiptype"] for r in all_rels)
        inverse_counts = Counter(
            r["inverserelationshiptype"]
            for r in all_rels
            if r["inverserelationshiptype"]
        )

        self.stdout.write("\n  Relationship types found in database:")
        for rel_type, count in type_counts.most_common():
            is_uuid = self._is_uuid(rel_type)
            type_label = "UUID" if is_uuid else "string"
            self.stdout.write(
                f"    - relationshiptype: {rel_type} ({type_label}): {count} occurrences"
            )

        if inverse_counts:
            self.stdout.write("\n  Inverse relationship types found:")
            for rel_type, count in inverse_counts.most_common():
                is_uuid = self._is_uuid(rel_type)
                type_label = "UUID" if is_uuid else "string"
                self.stdout.write(
                    f"    - inverserelationshiptype: {rel_type} ({type_label}): {count} occurrences"
                )
        else:
            self.stdout.write("\n  No inverse relationship types found (will use None)")

        # Decision logic
        uuid_types = [t for t in type_counts.keys() if self._is_uuid(t)]
        string_types = [t for t in type_counts.keys() if not self._is_uuid(t)]

        # Determine main relationship type
        if force_uuid and uuid_types:
            selected = uuid_types[0]
            self.stdout.write(
                self.style.SUCCESS(f"\n  ✓ Using UUID format (forced): {selected}")
            )
        elif uuid_types:
            most_common = type_counts.most_common(1)[0][0]
            if self._is_uuid(most_common):
                selected = most_common
                self.stdout.write(
                    self.style.SUCCESS(
                        f"\n  ✓ Using UUID format (most common): {selected}"
                    )
                )
            else:
                selected = uuid_types[0]
                self.stdout.write(
                    self.style.WARNING(
                        f"\n  ⚠️  String format '{most_common}' is most common, but using UUID: {selected}"
                    )
                )
        elif string_types:
            selected = type_counts.most_common(1)[0][0]
            self.stdout.write(
                self.style.WARNING(f"\n  ⚠️  Only string format found: '{selected}'")
            )
        else:
            selected = "ac41d9be-79db-4256-b368-2f4559cfbe55"

        # Determine inverse relationship type
        # For symmetric relations like "is related to", use same UUID
        # For asymmetric relations, they should be different
        inverse_selected = None

        if inverse_counts:
            # Get most common inverse
            most_common_inverse = inverse_counts.most_common(1)[0][0]

            # Check if it's the same as main type (symmetric relation)
            if most_common_inverse == selected:
                inverse_selected = selected
                self.stdout.write(f"  ✓ Symmetric relation (inverse same as main)")
            else:
                inverse_selected = most_common_inverse
                self.stdout.write(
                    f"  ✓ Asymmetric relation (inverse: {inverse_selected})"
                )
        else:
            # No inverse found, check if we should use same UUID (symmetric)
            # For "is related to" concept, it's typically symmetric
            if self._is_uuid(selected):
                # Try to determine if it's a symmetric concept
                try:
                    value = Value.objects.get(valueid=selected)
                    concept_label = value.value.lower()

                    # Common symmetric relation labels
                    symmetric_keywords = [
                        "related",
                        "connected",
                        "linked",
                        "associated",
                    ]
                    is_symmetric = any(kw in concept_label for kw in symmetric_keywords)

                    if is_symmetric:
                        inverse_selected = selected
                        self.stdout.write(
                            f'  ✓ Detected symmetric relation: "{value.value}"'
                        )
                        self.stdout.write(
                            f"    Using same UUID for inverse: {inverse_selected}"
                        )
                    else:
                        inverse_selected = None
                        self.stdout.write(
                            f'  ℹ Detected non-symmetric relation: "{value.value}"'
                        )
                        self.stdout.write(f"    No inverse type set (None)")
                except Value.DoesNotExist:
                    # Can't determine, default to None
                    inverse_selected = None
                    self.stdout.write(
                        f"  ℹ Cannot determine symmetry, inverse set to None"
                    )
            else:
                # String format, likely "related", assume symmetric
                inverse_selected = selected if selected == "related" else None
                if inverse_selected:
                    self.stdout.write(f'  ✓ Symmetric relation: "{selected}"')

        return (selected, inverse_selected)

    def _is_uuid(self, value):
        """Check if a value is a valid UUID"""
        try:
            UUID(str(value))
            return True
        except (ValueError, AttributeError):
            return False

    def handle(self, *args, **options):
        input_file = options["input"]
        dry_run = options["dry_run"]
        batch_size = options["batch_size"]
        skip_errors = options["skip_errors"]
        force_uuid = options["force_uuid"]

        # Inverted logic: include by default, exclude if flag is set
        include_tile = not options["exclude_tile"]
        include_node = not options["exclude_node"]
        include_notes = not options["exclude_notes"]

        # ✅ CORRECTION: Récupérer le tuple et décomposer
        manual_rel_type = options.get("relationship_type")
        manual_inverse_type = options.get("inverse_relationship_type")

        if manual_rel_type:
            # Type manuel spécifié
            relationship_type = manual_rel_type

            # Gérer l'inverse
            if manual_inverse_type:
                if manual_inverse_type.lower() == "none":
                    inverse_relationship_type = None
                else:
                    inverse_relationship_type = manual_inverse_type
            else:
                # Auto-détecter l'inverse pour le type manuel
                if self._is_uuid(relationship_type):
                    try:
                        value = Value.objects.get(valueid=relationship_type)
                        concept_label = value.value.lower()
                        symmetric_keywords = [
                            "related",
                            "connected",
                            "linked",
                            "associated",
                        ]
                        if any(kw in concept_label for kw in symmetric_keywords):
                            inverse_relationship_type = relationship_type
                            self.stdout.write(
                                f"\n  Detected symmetric relation from concept label"
                            )
                        else:
                            inverse_relationship_type = None
                    except Value.DoesNotExist:
                        inverse_relationship_type = None
                elif relationship_type == "related":
                    inverse_relationship_type = "related"
                else:
                    inverse_relationship_type = None
        else:
            # Auto-détection complète
            relationship_type, inverse_relationship_type = (
                self.get_default_relationship_type(force_uuid)
            )

        self.stdout.write("\n" + "=" * 80)
        self.stdout.write("IMPORT RELATIONSHIPS TO RESOURCEXRESOURCE")
        self.stdout.write("=" * 80)

        if dry_run:
            self.stdout.write(self.style.WARNING("\nMODE DRY RUN - No modifications\n"))

        self.stdout.write(f"\nInput file: {input_file}")

        # Afficher la configuration des types de relation
        is_uuid_format = self._is_uuid(relationship_type)
        self.stdout.write(f"\nRelationship configuration:")
        self.stdout.write(
            f"  - Main type: {relationship_type} ({'UUID' if is_uuid_format else 'string'})"
        )

        if is_uuid_format:
            try:
                value = Value.objects.get(valueid=relationship_type)
                self.stdout.write(f'    Concept: "{value.value}"')
            except Value.DoesNotExist:
                self.stdout.write(
                    self.style.WARNING(f"    ⚠️  Concept not found in RDM")
                )

        if inverse_relationship_type:
            is_inverse_uuid = self._is_uuid(inverse_relationship_type)
            self.stdout.write(
                f"  - Inverse type: {inverse_relationship_type} ({'UUID' if is_inverse_uuid else 'string'})"
            )

            if inverse_relationship_type == relationship_type:
                self.stdout.write(f"  - Relation is: SYMMETRIC (bidirectional)")
            else:
                self.stdout.write(f"  - Relation is: ASYMMETRIC (directional)")
        else:
            self.stdout.write(f"  - Inverse type: None")
            self.stdout.write(f"  - Relation is: DIRECTIONAL (one-way)")

        self.stdout.write(f"\nField inclusion:")
        self.stdout.write(
            f"  - Tile reference: {self.style.SUCCESS('YES') if include_tile else self.style.WARNING('NO')}"
        )
        self.stdout.write(
            f"  - Node reference: {self.style.SUCCESS('YES') if include_node else self.style.WARNING('NO')}"
        )
        self.stdout.write(
            f"  - Auto notes: {self.style.SUCCESS('YES') if include_notes else self.style.WARNING('NO')}"
        )
        self.stdout.write("")

        # Read CSV
        relations_to_create = []
        skipped_count = 0
        error_lines = 0

        with open(input_file, "r", encoding="utf-8") as csvfile:
            reader = csv.DictReader(csvfile)

            for row_num, row in enumerate(reader, start=2):
                action = row.get("action", "").strip().upper()
                status = row.get("status", "").strip().upper()

                if action == "SKIP":
                    skipped_count += 1
                    continue

                if action == "ERROR" or status in ["INVALID_TARGET", "ERROR"]:
                    error_lines += 1
                    continue

                if action == "CREATE":
                    relations_to_create.append(
                        {
                            "from_resource_id": row["source_id"].strip(),
                            "to_resource_id": row["target_id"].strip(),
                            "source_name": row.get("source_name", "").strip(),
                            "target_name": row.get("target_name", "").strip(),
                            "relation_type": row.get("relation_type", "").strip(),
                            "tile_id": (
                                row.get("tile_id", "").strip() if include_tile else None
                            ),
                            "node_id": (
                                row.get("node_id", "").strip() if include_node else None
                            ),
                            "row_num": row_num,
                        }
                    )

        total = len(relations_to_create)

        self.stdout.write(f"Relations to create: {total}")
        self.stdout.write(f"Relations skipped (SKIP): {skipped_count}")
        self.stdout.write(f"Error lines ignored: {error_lines}\n")

        if total == 0:
            self.stdout.write(self.style.WARNING("No relations to create!"))
            return

        if dry_run:
            self.stdout.write("Preview of relations to create:\n")
            for i, rel in enumerate(relations_to_create[:20], 1):
                tile_info = (
                    f" [tile: {rel['tile_id'][:8]}...]" if rel["tile_id"] else ""
                )
                node_info = (
                    f" [node: {rel['node_id'][:8]}...]" if rel["node_id"] else ""
                )
                self.stdout.write(
                    f"  {i}. {rel['relation_type']}: "
                    f"{rel['source_name'][:30]} → {rel['target_name'][:30]}"
                    f"{tile_info}{node_info}"
                )
            if total > 20:
                self.stdout.write(f"  ... and {total - 20} more")

            self.stdout.write("\n" + "=" * 80)
            self.stdout.write("END OF DRY RUN")
            self.stdout.write("=" * 80)
            self.stdout.write("To execute, run without --dry-run")
            return

        # Create relationships in batches
        created = 0
        existed = 0
        errors = 0
        error_details = []

        self.stdout.write("Creating relationships...\n")

        for i in range(0, total, batch_size):
            batch = relations_to_create[i : i + batch_size]
            batch_num = (i // batch_size) + 1
            total_batches = (total + batch_size - 1) // batch_size

            self.stdout.write(f"Batch {batch_num}/{total_batches}...")

            try:
                with transaction.atomic():
                    for rel in batch:
                        try:
                            # Verify resources exist
                            try:
                                from_res = Resource.objects.get(
                                    resourceinstanceid=rel["from_resource_id"]
                                )
                            except Resource.DoesNotExist:
                                raise Exception(
                                    f"Source resource not found: {rel['from_resource_id'][:8]}..."
                                )

                            try:
                                to_res = Resource.objects.get(
                                    resourceinstanceid=rel["to_resource_id"]
                                )
                            except Resource.DoesNotExist:
                                raise Exception(
                                    f"Target resource not found: {rel['to_resource_id'][:8]}..."
                                )

                            # Prepare optional fields
                            tile_obj = None
                            if include_tile and rel["tile_id"]:
                                try:
                                    tile_obj = Tile.objects.get(tileid=rel["tile_id"])
                                except Tile.DoesNotExist:
                                    if created == 0:
                                        self.stdout.write(
                                            self.style.WARNING(
                                                f"    ⚠️  Some tiles not found, continuing without tile references..."
                                            )
                                        )

                            node_obj = None
                            if include_node and rel["node_id"]:
                                try:
                                    node_obj = Node.objects.get(nodeid=rel["node_id"])
                                except Node.DoesNotExist:
                                    pass

                            # ✅ CORRECTION: Prepare notes (était mal placé avant)
                            notes_text = None
                            if include_notes:
                                notes_text = (
                                    f"Auto-imported from CSV on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}. "
                                    f"Source: {rel['source_name'][:50]} → Target: {rel['target_name'][:50]}"
                                )

                            # ✅ CORRECTION: Utiliser les valeurs correctes (pas de tuple!)
                            rxr, is_created = ResourceXResource.objects.get_or_create(
                                from_resource_id=rel["from_resource_id"],
                                to_resource_id=rel["to_resource_id"],
                                defaults={
                                    "from_resource_graph_id": from_res.graph_id,
                                    "to_resource_graph_id": to_res.graph_id,
                                    "tile": tile_obj,
                                    "node": node_obj,
                                    "relationshiptype": relationship_type,  # ✅ UUID simple, pas tuple!
                                    "inverserelationshiptype": inverse_relationship_type,  # ✅ UUID ou None
                                    "notes": notes_text,  # ✅ Maintenant correctement assigné
                                },
                            )

                            if is_created:
                                created += 1
                            else:
                                existed += 1

                        except Exception as e:
                            errors += 1
                            error_msg = f"Row {rel['row_num']}: {str(e)}"
                            error_details.append(error_msg)

                            if not skip_errors:
                                raise
                            else:
                                self.stdout.write(self.style.ERROR(f"  ✗ {error_msg}"))

                if (i + batch_size) % 500 == 0 or (i + batch_size) >= total:
                    self.stdout.write(
                        f"  Progress: {min(i + batch_size, total)}/{total} ({created} created)"
                    )

            except Exception as e:
                if not skip_errors:
                    self.stdout.write(
                        self.style.ERROR(
                            f"\n✗ Fatal error in batch {batch_num}: {str(e)}"
                        )
                    )
                    self.stdout.write(
                        "Import cancelled. Use --skip-errors to continue despite errors."
                    )
                    return

        # Summary
        self.stdout.write("\n" + "=" * 80)
        self.stdout.write("IMPORT SUMMARY")
        self.stdout.write("=" * 80)
        self.stdout.write(self.style.SUCCESS(f"✓ Relations created: {created}"))
        self.stdout.write(f"  Relations already existed: {existed}")
        self.stdout.write(f"\nRelationship types used:")
        self.stdout.write(f"  - relationshiptype: {relationship_type}")
        self.stdout.write(
            f"  - inverserelationshiptype: {inverse_relationship_type if inverse_relationship_type else 'None'}"
        )

        if errors > 0:
            self.stdout.write(self.style.ERROR(f"\n✗ Errors: {errors}"))

            if len(error_details) <= 10:
                self.stdout.write("\nError details:")
                for err in error_details:
                    self.stdout.write(f"  - {err}")
            else:
                self.stdout.write(f"\nFirst 10 errors:")
                for err in error_details[:10]:
                    self.stdout.write(f"  - {err}")
                self.stdout.write(f"  ... and {len(error_details) - 10} more errors")

        self.stdout.write("\n✓ Import complete!")
